### ISSUE TITLE
import issues

### ISSUE THREAD

**Issue by timmermansjoy** [kausko/Portfolio#11]
**Describe the bug**
when running the program locally. every time you connect the terminal gets flooded with messages. This also presumably causes the app to give an error every time it hot reloads

```
info  - ready on http://localhost:3000
event - build page: /
wait  - compiling...
warn  - ./pages/index.js
Should not import the named export 'name' (imported as 'name') from default-exporting module (only default export is available soon)

./src/About.js
Should not import the named export 'about'.'social'.'length' (imported as 'about') from default-exporting module (only default export is available soon)

./src/About.js
Should not import the named export 'about'.'social'.'map' (imported as 'about') from default-exporting module (only default export is available soon)

./src/About.js
Should not import the named export 'about'.'description' (imported as 'about') from default-exporting module (only default export is available soon)

./src/About.js
Should not import the named export 'about'.'picture' (imported as 'about') from default-exporting module (only default export is available soon)

./src/Experience.js
Should not import the named export 'experience' (imported as 'experience') from default-exporting module (only default export is available soon)

./src/Experience.js
Should not import the named export 'experience' (imported as 'experience') from default-exporting module (only default export is available soon)

./src/Landing.js
Should not import the named export 'landing'.'professionalDetails'.'map' (imported as 'landing') from default-exporting module (only default export is available soon)

./src/Landing.js
Should not import the named export 'landing'.'title' (imported as 'landing') from default-exporting module (only default export is available soon)

./src/Landing.js
Should not import the named export 'landing'.'subtitles' (imported as 'landing') from default-exporting module (only default export is available soon)

./src/Skills.js
Should not import the named export 'skills' (imported as 'skills') from default-exporting module (only default export is available soon)

./src/Skills.js
Should not import the named export 'skills' (imported as 'skills') from default-exporting module (only default export is available soon)
```

**To Reproduce**
1. Connect to your localhost with the browser after running `yarn && yarn dev`

**Comment by kausko** [comment]
Hello again.
I wasn't able to reproduce these warnings. However, I looked them up, and it seems like these have something to do with webpack and importing from json files. Maybe this is being caused by the parts of `data.json` that are being imported in different files. Anyway, it would be great if you could send the hot-reload error you mentioned in the issues as well.
Thanks

**Comment by timmermansjoy** [comment]
sorry for the late response. here is the error code you are asking about. It always shows up for 1-2 sec and then the site reloads itself again and then its fine again. 

![Screenshot 2021-11-07 at 5 25 49 PM](https://user-images.githubusercontent.com/61321383/140885817-e9d1adaa-b8f2-4690-9a7f-ae98ac393c6a.png)


also in the console there comes an error 

![Screenshot 2021-11-09 at 9 10 44 AM](https://user-images.githubusercontent.com/61321383/140886371-4dacdb5b-442d-47b9-be61-2c61e5a72cd1.png)

**Comment by kausko** [comment]
Solved the "text content did not match" SSR issue in #12 and the "Hot-reload" issue in #13. Feel free to close these issues if this worked out for you.

#11 showed up for me in Vercel's build logs post-deployment. Storing this data in a js object instead of a json file could work. It'll also increase the customizability of the theme object, since we'll be able to pass functions as well. But I'm not sure if this is the best way to solve this problem. What do you think @timmermansjoy?

**Comment by timmermansjoy** [comment]
from what I have seen is [this](https://stackoverflow.com/questions/64993118/error-should-not-import-the-named-export-version-imported-as-version) the issue. It worked for when I did it in `skills.js` but not for the rest and I didnt look further

**Comment by kausko** [comment]
> from what I have seen is [this](https://stackoverflow.com/questions/64993118/error-should-not-import-the-named-export-version-imported-as-version) the issue. It worked for when I did it in `skills.js` but not for the rest and I didnt look further

This method worked for me. I'm not getting any errors in the build process anymore. Thanks
